import { ChannelType, PermissionFlagsBits, PermissionsBitField, EmbedBuilder, AuditLogEvent } from 'discord.js';
import { guildConfig, LOG_CATEGORIES, saveState, state } from './store.js';
import { makeEmbed, safeReply, requirePermission, requireGuild, requireOwner, mentionedMember, mentionedUser, parseDuration, cleanMentionArgs, formatWelcome, isBotOwner, can, logEvent, setServerLock, getAuditExecutor, authorizedExecutor, auditOwner, COLORS } from './utils.js';

export const CATALOG = {
  'General':['ping','av','ab','poll','botinvite','serverinfo','afk','snipe','esnipe'],
  'Moderation':['kick','ban','unban','mute','unmute','warn','warnings','delwarn','clearwarnings','nick','purge','lock','unlock','hide','unhide','lockall','unlockall'],
  'Antinuke':['antinuke','antinuke setup','antinuke enable','antinuke disable','antinuke status','antinuke owner','antinuke whitelist','antinuke wlrole','antinuke punishment','antinuke logging','antinuke strict','antinuke lockdown','antinuke panic','antinuke recover'],
  'Antiraid':['antiraid','antiraid enable','antiraid disable','antiraid status','antiraid action','antiraid threshold','antiraid lockdown','antiraid age_limit','antiraid verification','antiraid avatar_check','antiraid delete_invites'],
  'AutoMod':['.automod','.antispam','.antispam enable','.antispam disable','.antispam wl add','.antispam wl remove','.antispam wl list','.antilink','.antilink enable','.antilink disable','.antilink wl add','.antilink wl remove','.antilink wl list','.antiword','.antiword enable','.antiword disable','.antiword add','.antiword remove','.antiword list','.antiword wl add','.antiword wl remove','.antiword wl list','.automod punishment'],
  'Tickets':[], 'Welcome':['welcomer','welcomer channel','welcomer message','welcomer image','welcomer embed','welcomer test'],
  'Logging':['logging','logging enable','logging disable','logging enableall','logging disableall','logging categories'],
  'Embed':[], 'Social':[], 'Utility':['view','myperms','viewperms','botperms','list admins','listadmins','viewroles','prefix','prefix set','prefix reset','prefix show','prefix add','prefix remove','setprefix','botsettings'],
  'Custom Branding':[], 'Owners Only':['/owner lockdown','/owner unlock','/owner slowmode-all','/owner emergency','/owner add <user>','/owner remove <user>','/owner list','/owner transfer','/owner permissions','/owner audit'],
  'Roles':['role','role add','role remove','role create','role delete','role colour','role rename','role all','role bots','role humans','role info','role list','createrole'],
  'Join2Create':[], 'Tracking':['leaderboard','viewuser','setidentity','removeidentity','adminview','modview'],
  'Voice':['vckick','vcpull','vcmute','vcdeafen','vcpullall','vckickall','vcdeafenall','vcrole','vcrole add','vcrole remove','vcrole show']
};
export const TOTAL_COMMANDS = Object.values(CATALOG).reduce((n,a)=>n+a.length,0);

export function helpText(prefix, context='') {
  const key=Object.keys(CATALOG).find(k=>k.toLowerCase()===String(context).toLowerCase());
  const header=`• **My prefix for this server is** \`${prefix}\` **• Type** \`${prefix}help [context]\` **for more**\n• **Total commands:** **${TOTAL_COMMANDS}**`;
  if(!key) return `${header}\n\n${Object.entries(CATALOG).map(([k,v])=>`${icon(k)} » **${k}**${v.length?` — ${v.length}`:''}`).join('\n')}`;
  const guide={General:'Essential everyday tools. Check server metrics, inspect member avatars/banners, view ping latencies, build custom polls, fetch invitation links, or snipe messages and steal emojis.',Moderation:'Maintain server order. Warnings, warning purges, message purges, channel locking/hiding, nickname controls, and member timeout/kick/ban actions.',Antinuke:'Protect against malicious administrator actions and recover deleted server structure.',Antiraid:'Protect against mass-join raids, suspicious accounts, bot waves, configurable thresholds, account age and lockdown.',AutoMod:'Automated filters for links, spam and bad words with whitelists and punishments.',Welcome:'Welcome new members with placeholders and custom message/image/embed settings.',Logging:'Keep tabs on server events across 13 distinct logging categories.',Utility:'Manage prefixes, permissions, administrator lists and server utilities.',Voice:'Keep voice rooms under control. Deafen, mute, kick, pull and configure voice roles.',Tracking:'Track member message volumes and inspect contribution/profile statistics.',Roles:'Manage roles, colours, names and bulk assignments.',Tickets:'No command list was specified in the requested feature list.',Embed:'No command list was specified in the requested feature list.',Social:'No command list was specified in the requested feature list.','Custom Branding':'No command list was specified in the requested feature list.',Join2Create:'No command list was specified in the requested feature list.','Owners Only':'Owner-only server control and bot ownership commands.'}[key]||'';
  return `${header}\n\n${icon(key)} » **${key}**\n💡 **Guide:** ${guide}\n\n**Commands:**\n${CATALOG[key].length?CATALOG[key].map(x=>`• \`${x}\``).join('\n'):'• None specified.'}`;
}
function icon(k){return ({General:'🌐',Moderation:'🛡️',Antinuke:'⚡',Antiraid:'🚨',AutoMod:'🤖',Tickets:'🎫',Welcome:'👋',Logging:'📜',Embed:'🎨',Social:'💬',Utility:'🛠️','Custom Branding':'✨','Owners Only':'👑',Roles:'🎭',Join2Create:'🔊',Tracking:'📊',Voice:'🎙️'})[k]||'•';}

export async function handlePrefix(message, name, args, client) {
  const g=message.guild; if(!g)return;
  const c=guildConfig(g.id), member=message.member;
  if(name==='help'||name==='h') return safeReply(message,{embeds:[makeEmbed('Kiara Help',helpText(c.prefix,args.join(' '))) ]});
  // General
  if(name==='ping')return safeReply(message,`🏓 Pong! **${Math.round(client.ws.ping)}ms**`);
  if(name==='av'){const u=mentionedUser(message)||message.author;const url=u.displayAvatarURL({size:4096,extension:'png'});return safeReply(message,{embeds:[makeEmbed(`${u.username}'s Avatar`,`[Open full size](${url})`).setImage(url)]});}
  if(name==='ab'){const u=mentionedUser(message)||message.author;const full=await client.users.fetch(u.id,{force:true}).catch(()=>u);const url=full.bannerURL({size:4096,extension:'png'});return safeReply(message,url?{embeds:[makeEmbed(`${u.username}'s Banner`,`[Open full size](${url})`).setImage(url)]}:'❌ This user has no banner.');}
  if(name==='poll'){if(!args.length)return safeReply(message,`Usage: \`${c.prefix}poll <question>\``);const m=await message.channel.send({embeds:[makeEmbed('📊 Poll',args.join(' '))],content:'👍 **Yes**   👎 **No**'});await m.react('👍').catch(()=>{});await m.react('👎').catch(()=>{});return;}
  if(name==='botinvite'){return safeReply(message,`🔗 https://discord.com/oauth2/authorize?client_id=${client.user.id}&scope=bot%20applications.commands&permissions=8`);}
  if(name==='serverinfo'){return safeReply(message,{embeds:[makeEmbed(`📊 ${g.name}`,`**Owner:** <@${g.ownerId}>\n**Members:** ${g.memberCount}\n**Channels:** ${g.channels.cache.size}\n**Roles:** ${g.roles.cache.size}\n**Boosts:** ${g.premiumSubscriptionCount||0}\n**Created:** <t:${Math.floor(g.createdTimestamp/1000)}:F>\n**ID:** \`${g.id}\``)]});}
  if(name==='afk'){const reason=args.join(' ')||'AFK';c.afk ||= {};c.afk[message.author.id]={reason,at:Date.now()};await saveState();return safeReply(message,`💤 AFK set: **${reason}**`);}
  if(name==='snipe'||name==='esnipe'){const map=name==='snipe'?client.deleted:client.edited;const x=map.get(message.channel.id);return safeReply(message,x?{embeds:[makeEmbed(name==='snipe'?'🗑️ Deleted Message':'✏️ Edited Message',name==='snipe'?`**${x.author}**\n${x.content||'*No text*'}`:`**${x.author}**\nBefore: ${x.before||'*No text*'}\nAfter: ${x.after||'*No text*'}`)]}:'❌ Nothing to snipe.');}
  // Moderation
  if(['kick','ban','mute','unmute','warn','warnings','delwarn','clearwarnings','nick'].includes(name)){
    const perm=(name==='kick'?PermissionFlagsBits.KickMembers:name==='ban'||name==='unban'||name==='delwarn'?PermissionFlagsBits.BanMembers: name==='mute'||name==='unmute'?PermissionFlagsBits.ModerateMembers: name==='nick'?PermissionFlagsBits.ManageNicknames:PermissionFlagsBits.ModerateMembers);
    if(!await requirePermission(message,perm))return;
  }
  if(name==='unban'){if(!await requirePermission(message,PermissionFlagsBits.BanMembers))return;const id=(args[0]||'').replace(/\D/g,'');if(!id)return safeReply(message,`Usage: \`${c.prefix}unban <user ID>\``);try{await g.members.unban(id);return safeReply(message,'✅ User unbanned.')}catch(e){return safeReply(message,`❌ ${e.message}`)}}
  if(['kick','ban','mute','unmute'].includes(name)){const m=mentionedMember(message);if(!m||m.id===g.ownerId||member.roles.highest.comparePositionTo(m.roles.highest)<=0)return safeReply(message,'❌ Mention a member you can manage.');const reason=cleanMentionArgs(args).filter(x=>!/^\d+[smhd]$/i.test(x)).join(' ')||'No reason provided';try{if(name==='kick')await m.kick(reason);if(name==='ban')await m.ban({reason});if(name==='mute')await m.timeout(parseDuration(args.find(x=>/^\d+[smhd]$/i.test(x)))||3600000,reason);if(name==='unmute')await m.timeout(null,reason);await logEvent(g,'moderation','🛡️ Moderation action',`${message.author} used **${name}** on ${m}.\nReason: ${reason}`);return safeReply(message,`✅ ${name} completed for **${m.user.tag}**.`)}catch(e){return safeReply(message,`❌ ${e.message}`)}}
  if(name==='warn'){const m=mentionedMember(message);if(!m||m.id===message.author.id)return safeReply(message,'❌ Mention a member.');const reason=cleanMentionArgs(args).join(' ')||'No reason provided';c.warnings[m.id] ||= [];const id=Date.now().toString(36);c.warnings[m.id].push({id,moderator:message.author.id,reason,at:Date.now()});await saveState();await logEvent(g,'moderation','⚠️ Warning',`${m} was warned by ${message.author}.\nReason: ${reason}`);return safeReply(message,`⚠️ Warned ${m} — ID \`${id}\``)}
  if(name==='warnings'){const m=mentionedMember(message)||member;const ws=c.warnings[m.id]||[];return safeReply(message,{embeds:[makeEmbed(`Warnings: ${m.user.tag}`,ws.length?ws.map((w,i)=>`**${i+1}.** \`${w.id}\` — ${w.reason} — <@${w.moderator}>`).join('\n'):'No warnings.')]});}
  if(name==='delwarn'){const id=args[0];if(!id)return safeReply(message,`Usage: \`${c.prefix}delwarn <ID>\``);let found=false;for(const uid of Object.keys(c.warnings)){const old=c.warnings[uid]||[];const nw=old.filter(w=>w.id!==id);if(nw.length!==old.length){c.warnings[uid]=nw;found=true;}}await saveState();return safeReply(message,found?'✅ Warning deleted.':'❌ Warning ID not found.')}
  if(name==='clearwarnings'){const m=mentionedMember(message);if(!m)return safeReply(message,'Mention a member.');c.warnings[m.id]=[];await saveState();return safeReply(message,'✅ Warnings cleared.')}
  if(name==='nick'){const sub=args[0]?.toLowerCase(),m=mentionedMember(message);if(sub==='lock'||sub==='unlock'){if(!m)return safeReply(message,'Mention a member.');c.nickLocks=sub==='lock'?[...new Set([...c.nickLocks,m.id])]:c.nickLocks.filter(x=>x!==m.id);await saveState();return safeReply(message,`✅ Nick lock ${sub}ed for ${m}.`);}if(!m)return safeReply(message,`Usage: \`${c.prefix}nick @user <nickname>\``);try{await m.setNickname(args.slice(1).join(' ')||null,'Nickname command');return safeReply(message,'✅ Nickname updated.')}catch(e){return safeReply(message,`❌ ${e.message}`)}}
  if(name==='purge'){if(!await requirePermission(message,PermissionFlagsBits.ManageMessages))return;const fetched=await message.channel.messages.fetch({limit:100});let arr=[];if(args[0]?.toLowerCase()==='bot')arr=[...fetched.values()].filter(m=>m.author.bot);else {const u=mentionedUser(message);const n=Math.min(Math.max(Number(args.find(x=>/^\d+$/.test(x)))||10,1),100);arr=u?[...fetched.values()].filter(m=>m.author.id===u.id).slice(0,n):[...fetched.values()].slice(0,n);}await message.channel.bulkDelete(arr,true);return safeReply(message,`🧹 Deleted **${arr.length}** messages.`)}
  if(['lock','unlock','hide','unhide'].includes(name)){if(!await requirePermission(message,PermissionFlagsBits.ManageChannels))return;const on=name==='lock'||name==='hide';await message.channel.permissionOverwrites.edit(g.roles.everyone,{SendMessages:name==='lock'?(on?false:null):name==='unlock'?null:undefined,ViewChannel:name==='hide'?false:name==='unhide'?null:undefined});return safeReply(message,`✅ Channel ${name}ed.`)}
  if(name==='lockall'||name==='unlockall'){if(!await requirePermission(message,PermissionFlagsBits.ManageChannels))return;for(const ch of g.channels.cache.values())if(ch.type===ChannelType.GuildText)await ch.permissionOverwrites.edit(g.roles.everyone,{SendMessages:name==='lockall'?false:null}).catch(()=>{});return safeReply(message,`✅ All text channels ${name==='lockall'?'locked':'unlocked'}.`)}

  // Security/utility dispatch
  if(['antinuke','antiraid','welcomer','logging','automod','antispam','antilink','antiword'].includes(name))return securityCommand(message,name,args);
  if(['view','myperms','viewperms','botperms','list','listadmins','viewroles','prefix','setprefix','botsettings','leaderboard','viewuser','setidentity','removeidentity','adminview','modview','vckick','vcpull','vcmute','vcdeafen','vcpullall','vckickall','vcdeafenall','vcrole','role','createrole'].includes(name))return utilityCommand(message,name,args);
  return safeReply(message,`❓ Unknown command. Use \`${c.prefix}help\`.`);
}

async function securityCommand(message,name,args){
  const g=message.guild,c=guildConfig(g.id),sub=(args[0]||'').toLowerCase();
  if(['antinuke','antiraid','welcomer','logging','automod','antispam','antilink','antiword'].includes(name)&&!await requirePermission(message,PermissionFlagsBits.ManageGuild))return;
  if(name==='antinuke'){
    if(!sub)return safeReply(message,{embeds:[makeEmbed('⚡ Antinuke',`Enabled: **${c.antinuke.enabled}**\nPunishment: **${c.antinuke.punishment}**\nStrict: **${c.antinuke.strict}**\nLockdown: **${c.antinuke.lockdown}**\nPanic: **${c.antinuke.panic}**`)]});
    if(sub==='setup')return setupAntinuke(message,c);
    if(['enable','disable'].includes(sub)){c.antinuke.enabled=sub==='enable';await saveState();return safeReply(message,`🛡️ Antinuke ${sub}d.`)}
    if(sub==='status')return safeReply(message,{embeds:[makeEmbed('⚡ Antinuke Status',JSON.stringify(c.antinuke,null,2))]});
    if(sub==='owner')return safeReply(message,'👑 The server owner and configured bot owners are trusted by antinuke.');
    if(sub==='whitelist'||sub==='wlrole'){const u=mentionedUser(message),r=message.mentions.roles.first();if(u&&!c.antinuke.whitelistUsers.includes(u.id))c.antinuke.whitelistUsers.push(u.id);else if(r&&!c.antinuke.whitelistRoles.includes(r.id))c.antinuke.whitelistRoles.push(r.id);else if(!u&&!r)return safeReply(message,'Mention a user or role.');await saveState();return safeReply(message,'✅ Whitelist updated.')}
    if(sub==='punishment'){const x=args[1]?.toLowerCase();if(!['ban','kick','striproles'].includes(x))return safeReply(message,'Use `ban`, `kick`, or `striproles`.');c.antinuke.punishment=x;await saveState();return safeReply(message,`✅ Punishment set to **${x}**.`)}
    if(sub==='logging'){c.antinuke.logChannelId=message.mentions.channels.first()?.id||args[1]||message.channel.id;c.logging.antinuke=c.antinuke.logChannelId;await saveState();return safeReply(message,'✅ Antinuke log channel set.')}
    if(sub==='strict'){c.antinuke.strict=!c.antinuke.strict;await saveState();return safeReply(message,`✅ Strict: **${c.antinuke.strict}**`) }
    if(sub==='lockdown'){c.antinuke.lockdown=!c.antinuke.lockdown;await setServerLock(g,c.antinuke.lockdown,'Antinuke lockdown');return safeReply(message,`✅ Lockdown: **${c.antinuke.lockdown}**`)}
    if(sub==='panic'){c.antinuke.panic=true;c.antinuke.strict=true;c.antinuke.enabled=true;await setServerLock(g,true,'Antinuke panic');await saveState();return safeReply(message,'🚨 Antinuke panic enabled.')}
    if(sub==='recover'){c.antinuke.panic=false;c.antinuke.strict=false;c.antinuke.lockdown=false;c.emergency=false;await setServerLock(g,false,'Antinuke recovery');await restoreSnapshot(g);await saveState();return safeReply(message,'🟢 Recovery completed.')}
  }
  if(name==='antiraid'){
    if(!sub)return safeReply(message,{embeds:[makeEmbed('🚨 Antiraid',`Enabled: **${c.antiraid.enabled}**\nAction: **${c.antiraid.action}**\nThreshold: **${c.antiraid.threshold}** in **${c.antiraid.windowSeconds}s**\nAge limit: **${c.antiraid.ageLimit} days**\nLockdown: **${c.antiraid.lockdown}**`)]});
    if(sub==='enable'||sub==='disable'){c.antiraid.enabled=sub==='enable';await saveState();return safeReply(message,`✅ Antiraid ${sub}d.`)}
    if(sub==='status')return safeReply(message,{embeds:[makeEmbed('🚨 Antiraid Status',JSON.stringify(c.antiraid,null,2))]});
    if(sub==='action'){if(!['kick','ban'].includes(args[1]))return safeReply(message,'Use `kick` or `ban`.');c.antiraid.action=args[1];await saveState();return safeReply(message,'✅ Action updated.')}
    if(sub==='threshold'){const n=Number(args[1]);if(!Number.isInteger(n)||n<2)return safeReply(message,'Usage: `!antiraid threshold <number>`');c.antiraid.threshold=Math.min(n,100);await saveState();return safeReply(message,'✅ Threshold updated.')}
    if(sub==='lockdown'){c.antiraid.lockdown=!c.antiraid.lockdown;await setServerLock(g,c.antiraid.lockdown,'Antiraid lockdown');return safeReply(message,'✅ Lockdown updated.')}
    if(sub==='age_limit'){const n=Number(args[1]);if(!Number.isFinite(n)||n<0)return safeReply(message,'Usage: `!antiraid age_limit <days>`');c.antiraid.ageLimit=n;await saveState();return safeReply(message,'✅ Age limit updated.')}
    if(['verification','avatar_check','delete_invites'].includes(sub)){c.antiraid[sub]=!c.antiraid[sub];await saveState();return safeReply(message,`✅ ${sub}: **${c.antiraid[sub]}**`)}
  }
  if(name==='welcomer'){
    if(!sub){c.welcome.enabled=!c.welcome.enabled;await saveState();return safeReply(message,`👋 Welcomer ${c.welcome.enabled?'enabled':'disabled'}.`)}
    if(sub==='channel'){c.welcome.channelId=message.mentions.channels.first()?.id||args[1]||message.channel.id;c.welcome.enabled=true;await saveState();return safeReply(message,'✅ Welcome channel set.')}
    if(sub==='message'){c.welcome.message=args.slice(1).join(' ')||args.join(' ');await saveState();return safeReply(message,'✅ Welcome message saved.')}
    if(sub==='image'){c.welcome.image=args[1]||null;await saveState();return safeReply(message,'✅ Welcome image saved.')}
    if(sub==='embed'){c.welcome.embed=args.slice(1).join(' ')||args.join(' ');await saveState();return safeReply(message,'✅ Welcome embed saved.')}
    if(sub==='test'){const m=mentionedMember(message)||message.member;const ch=g.channels.cache.get(c.welcome.channelId)||message.channel;const e=makeEmbed('👋 Welcome',formatWelcome(c.welcome.message,m));if(c.welcome.image)e.setImage(c.welcome.image);if(c.welcome.embed)e.addFields({name:'Saved embed',value:c.welcome.embed});await ch.send({embeds:[e]}).catch(()=>{});return safeReply(message,'✅ Welcome tested.')}
  }
  if(name==='logging'){
    if(!sub||sub==='categories')return safeReply(message,`**Logging categories:** ${LOG_CATEGORIES.join(', ')}`);
    if(sub==='enableall'){const ch=message.mentions.channels.first()||message.channel;for(const x of LOG_CATEGORIES)c.logging[x]=ch.id;await saveState();return safeReply(message,'✅ All logging categories enabled.')}
    if(sub==='disableall'){for(const x of LOG_CATEGORIES)c.logging[x]=null;await saveState();return safeReply(message,'✅ All logging categories disabled.')}
    if(sub==='enable'||sub==='disable'){const cat=args[1];if(!LOG_CATEGORIES.includes(cat))return safeReply(message,`❌ Category must be one of: ${LOG_CATEGORIES.join(', ')}`);c.logging[cat]=sub==='enable'?(message.mentions.channels.first()?.id||args[2]||message.channel.id):null;await saveState();return safeReply(message,`✅ ${cat} logging ${sub}d.`)}
  }
  if(['antispam','antilink','antiword','automod'].includes(name)){
    const key=name==='automod'?'antispam':name;
    if(name==='automod'&&sub==='punishment'){const p=args[1]||'delete';if(!['delete','timeout','warn'].includes(p))return safeReply(message,'Use `delete`, `timeout`, or `warn`.');c.automod.punishment=p;await saveState();return safeReply(message,`✅ Automod punishment: **${p}**`)}
    if(sub==='enable'||sub==='disable'){c.automod[key]=sub==='enable';await saveState();return safeReply(message,`✅ ${name} ${sub}d.`)}
    if(sub==='add'&&name==='antiword'){const w=args.slice(1).join(' ').toLowerCase();if(!w)return safeReply(message,'Provide a word.');if(!c.automod.words.includes(w))c.automod.words.push(w);await saveState();return safeReply(message,'✅ Bad word added.')}
    if(sub==='remove'&&name==='antiword'){const w=args.slice(1).join(' ').toLowerCase();c.automod.words=c.automod.words.filter(x=>x!==w);await saveState();return safeReply(message,'✅ Bad word removed.')}
    if(sub==='list'&&name==='antiword')return safeReply(message,`**Bad words:** ${c.automod.words.join(', ')||'None'}`);
    if(sub==='wl'){const action=args[1],u=mentionedUser(message),r=message.mentions.roles.first();const target=u?.id||r?.id;if(!target)return safeReply(message,'Mention a user or role.');const arr=u?c.automod.whitelists[key].users:c.automod.whitelists[key].roles;if(action==='add'&&!arr.includes(target))arr.push(target);if(action==='remove')c.automod.whitelists[key][u?'users':'roles']=arr.filter(x=>x!==target);await saveState();return safeReply(message,`✅ ${name} whitelist updated.`)}
    return safeReply(message,{embeds:[makeEmbed(`🤖 ${name}`,`Enabled: **${c.automod[key]}**\nWhitelisted users: ${c.automod.whitelists[key].users.length}\nWhitelisted roles: ${c.automod.whitelists[key].roles.length}`)]});
  }
}

async function setupAntinuke(message,c){
  const ask=async(text)=>{await safeReply(message,text);return new Promise(resolve=>{const col=message.channel.createMessageCollector({filter:m=>m.author.id===message.author.id&&m.channel.id===message.channel.id,time:60000,max:1});col.on('collect',m=>resolve(m));col.on('end',collected=>{if(!collected.size)resolve(null)});});};
  const a=await ask('⚡ **Antinuke Setup — Step 1/4** Enable? `yes/no`');if(!a)return safeReply(message,'❌ Setup timed out.');c.antinuke.enabled=['yes','y'].includes(a.content.toLowerCase());
  const b=await ask('**Step 2/4** Punishment? `ban/kick/striproles`');if(!b)return safeReply(message,'❌ Setup timed out.');if(['ban','kick','striproles'].includes(b.content.toLowerCase()))c.antinuke.punishment=b.content.toLowerCase();
  const d=await ask('**Step 3/4** Strict mode? `yes/no`');if(!d)return safeReply(message,'❌ Setup timed out.');c.antinuke.strict=['yes','y'].includes(d.content.toLowerCase());
  const e=await ask('**Step 4/4** Use this channel for antinuke logs? `yes/no`');if(!e)return safeReply(message,'❌ Setup timed out.');if(['yes','y'].includes(e.content.toLowerCase())){c.antinuke.logChannelId=message.channel.id;c.logging.antinuke=message.channel.id;}await saveState();return safeReply(message,'✅ Antinuke setup complete.');
}

async function utilityCommand(message,name,args){
  const g=message.guild,c=guildConfig(g.id),sub=(args[0]||'').toLowerCase();
  if(name==='view')return safeReply(message,{embeds:[makeEmbed('🛠️ View','`!myperms`\n`!viewperms @user`\n`!botperms`\n`!list admins`\n`!viewroles`')]});
  if(name==='myperms')return safeReply(message,`**Your permissions:** ${message.member.permissions.toArray().join(', ')||'None'}`);
  if(name==='viewperms'){const m=mentionedMember(message);return safeReply(message,m?`**${m.user.tag}:** ${m.permissions.toArray().join(', ')}`:'Mention a member.')}
  if(name==='botperms')return safeReply(message,`**Bot:** ${g.members.me?.permissions.toArray().join(', ')||'None'}`);
  if(name==='listadmins'||(name==='list'&&sub==='admins')){const list=[...g.members.cache.values()].filter(m=>m.permissions.has(PermissionFlagsBits.Administrator));return safeReply(message,{embeds:[makeEmbed('👑 Administrators',`**Humans:**\n${list.filter(m=>!m.user.bot).map(m=>m.toString()).join(', ')||'None'}\n\n**Bots:**\n${list.filter(m=>m.user.bot).map(m=>m.toString()).join(', ')||'None'}`)]});}
  if(name==='viewroles'){if(!can(message.member,PermissionFlagsBits.ManageGuild))return safeReply(message,'❌ Manage Server required.');return safeReply(message,{embeds:[makeEmbed('🎭 Roles',[...g.roles.cache.values()].sort((a,b)=>b.position-a.position).slice(0,50).map(r=>`${r} — ${r.members.size} members — ${r.permissions.has(PermissionFlagsBits.Administrator)?'ADMIN':''}`).join('\n'))]});}
  if(name==='prefix'||name==='setprefix'){if(!can(message.member,PermissionFlagsBits.ManageGuild))return safeReply(message,'❌ Manage Server required.');if(name==='setprefix'){const p=args[0];if(!p||p.length>5)return safeReply(message,'❌ Prefix must be 1–5 characters.');c.prefix=p;await saveState();return safeReply(message,`✅ Prefix set to \`${p}\`.`);}if(!sub)return safeReply(message,`Prefix: \`${c.prefix}\``);if(sub==='set'||sub==='add'){const p=args[1];if(!p||p.length>5)return safeReply(message,'❌ Prefix must be 1–5 characters.');c.prefix=p;}else if(sub==='reset'||sub==='remove')c.prefix='!';else if(sub==='show')return safeReply(message,`Prefix: \`${c.prefix}\``);await saveState();return safeReply(message,`✅ Prefix is now \`${c.prefix}\`.`);}
  if(name==='botsettings')return safeReply(message,{embeds:[makeEmbed('🛠️ Bot Settings',`Prefix: \`${c.prefix}\`\nUse \`${c.prefix}help\` for all requested categories.`)]});
  if(name==='leaderboard'){const entries=Object.entries(c.tracking.messages).sort((a,b)=>b[1]-a[1]).slice(0,10);return safeReply(message,{embeds:[makeEmbed('📊 Message Leaderboard',entries.map((x,i)=>`**${i+1}.** <@${x[0]}> — ${x[1]} messages`).join('\n')||'No data.')]});}
  if(name==='viewuser'){if(!can(message.member,PermissionFlagsBits.Administrator))return safeReply(message,'❌ Administrator required.');const m=mentionedMember(message)||message.member;return safeReply(message,{embeds:[makeEmbed('👤 User Profile',`User: ${m}\nID: \`${m.id}\`\nJoined: <t:${Math.floor((m.joinedTimestamp||Date.now())/1000)}:F>\nMessages: **${c.tracking.messages[m.id]||0}**\nIdentity: ${c.identities[m.id]||'Not set'}`)]});}
  if(name==='setidentity'||name==='removeidentity'){if(!can(message.member,PermissionFlagsBits.Administrator))return safeReply(message,'❌ Administrator required.');const m=mentionedMember(message)||message.member;if(name==='setidentity')c.identities[m.id]=args.slice(1).join(' ')||args.join(' ');else delete c.identities[m.id];await saveState();return safeReply(message,'✅ Identity updated.')}
  if(name==='adminview'||name==='modview'){if(!can(message.member,PermissionFlagsBits.ManageGuild))return safeReply(message,'❌ Manage Server required.');const list=[...g.members.cache.values()].filter(m=>name==='adminview'?m.permissions.has(PermissionFlagsBits.Administrator):(m.permissions.has(PermissionFlagsBits.ManageGuild)||m.permissions.has(PermissionFlagsBits.ManageMessages)));return safeReply(message,{embeds:[makeEmbed(name==='adminview'?'👑 Admin View':'🛡️ Mod View',list.map(m=>m.toString()).join(', ')||'None')]});}
  if(['vckick','vcpull','vcmute','vcdeafen','vcpullall','vckickall','vcdeafenall'].includes(name)){if(!await requirePermission(message,PermissionFlagsBits.MoveMembers))return;const from=message.member.voice.channel;if(!from)return safeReply(message,'❌ You are not in a voice channel.');const target=mentionedMember(message);if(name==='vcpullall'){for(const ch of g.channels.cache.values())if(ch.isVoiceBased())for(const m of ch.members.values())if(m.id!==message.author.id)await m.voice.setChannel(from).catch(()=>{});}else if(name==='vckickall'||name==='vcdeafenall'){for(const m of from.members.values()){if(name==='vckickall')await m.voice.disconnect().catch(()=>{});else await m.voice.setDeaf(true).catch(()=>{});}}else{if(!target)return safeReply(message,'Mention a voice member.');if(name==='vckick')await target.voice.disconnect();if(name==='vcpull')await target.voice.setChannel(from);if(name==='vcmute')await target.voice.setMute(true);if(name==='vcdeafen')await target.voice.setDeaf(true);}return safeReply(message,'✅ Voice action completed.');}
  if(name==='vcrole'){if(!can(message.member,PermissionFlagsBits.ManageRoles))return safeReply(message,'❌ Manage Roles required.');if(sub==='add'){const r=message.mentions.roles.first();if(!r)return safeReply(message,'Mention a role.');c.vcrole=r.id;await saveState();return safeReply(message,'✅ Voice role set.')}if(sub==='remove'){c.vcrole=null;await saveState();return safeReply(message,'✅ Voice role removed.')}return safeReply(message,`Voice role: ${c.vcrole?`<@&${c.vcrole}>`:'None'}`)}
  if(name==='createrole'||name==='role'){if(!await requirePermission(message,PermissionFlagsBits.ManageRoles))return; if(name==='createrole'){const r=await g.roles.create({name:args.join(' ')||'New Role',reason:'Role command'});return safeReply(message,`✅ Created ${r}.`)}const action=sub;if(action==='create'){const r=await g.roles.create({name:args.slice(1).join(' ')||'New Role'});return safeReply(message,`✅ Created ${r}.`)}const r=message.mentions.roles.first()||g.roles.cache.find(x=>x.name===args[1]);const u=mentionedMember(message);if(['add','remove'].includes(action)){if(!r||!u)return safeReply(message,'Mention a user and role.');if(action==='add')await u.roles.add(r);else await u.roles.remove(r);return safeReply(message,'✅ Role updated.')}if(action==='delete'){if(!r)return safeReply(message,'Mention a role.');await r.delete();return safeReply(message,'✅ Role deleted.')}if(action==='colour'){if(!r)return safeReply(message,'Mention a role.');await r.setColor(args[2]||args[1]);return safeReply(message,'✅ Role colour updated.')}if(action==='rename'){if(!r)return safeReply(message,'Mention a role.');await r.setName(args.slice(2).join(' '));return safeReply(message,'✅ Role renamed.')}if(['all','bots','humans'].includes(action)){if(!r)return safeReply(message,'Mention a role.');for(const m of g.members.cache.values()){if(action==='bots'&&!m.user.bot)continue;if(action==='humans'&&m.user.bot)continue;await m.roles.add(r).catch(()=>{});}return safeReply(message,'✅ Bulk role update completed.')}if(action==='info'){if(!r)return safeReply(message,'Mention a role.');return safeReply(message,{embeds:[makeEmbed('🎭 Role Info',`Name: ${r.name}\nID: \`${r.id}\`\nMembers: ${r.members.size}\nColour: ${r.hexColor}\nPosition: ${r.position}\nMentionable: ${r.mentionable}`)]});}return safeReply(message,{embeds:[makeEmbed('🎭 Roles',[...g.roles.cache.values()].sort((a,b)=>b.position-a.position).map(r=>`${r} — ${r.members.size}`).join('\n').slice(0,4000)||'No roles.')]});}
}

export async function restoreSnapshot(g){
  const snap=guildConfig(g.id).snapshot;if(!snap)return 0;let n=0;const names=new Set(g.roles.cache.map(r=>r.name));for(const r of snap.roles){if(names.has(r.name)||r.name==='@everyone')continue;try{await g.roles.create({name:r.name,color:r.color,hoist:r.hoist,mentionable:r.mentionable,permissions:BigInt(r.permissions),reason:'Automatic disaster recovery'});n++;}catch{}}
  const cats=new Map();for(const c of snap.channels.filter(x=>x.type===ChannelType.GuildCategory).sort((a,b)=>a.position-b.position)){let ch=g.channels.cache.find(x=>x.type===ChannelType.GuildCategory&&x.name===c.name);if(!ch)try{ch=await g.channels.create({name:c.name,type:ChannelType.GuildCategory,reason:'Automatic disaster recovery'});n++;}catch{}if(ch)cats.set(c.id,ch);}
  for(const c of snap.channels.filter(x=>x.type!==ChannelType.GuildCategory).sort((a,b)=>a.position-b.position)){if(g.channels.cache.find(x=>x.name===c.name&&x.type===c.type))continue;try{const o={name:c.name,type:c.type,parent:cats.get(c.parentId),reason:'Automatic disaster recovery'};if(c.type===ChannelType.GuildText){o.topic=c.topic||undefined;o.nsfw=c.nsfw;o.rateLimitPerUser=c.rateLimitPerUser||0;}if(c.type===ChannelType.GuildVoice){o.bitrate=c.bitrate||64000;o.userLimit=c.userLimit||0;}await g.channels.create(o);n++;}catch{}}
  await logEvent(g,'antinuke','🛠️ Disaster Recovery',`Best-effort recovery restored **${n}** missing server items.`,COLORS.good);return n;
}
